version: '3'

services:
    php:
        image: php:7.3-apache
        volumes: 
            - /home/hiro/Documents/docker/my-bookmarks:/var/www/html
        ports:
            - "80:80"
        container_name: my-bookmarks
