version: '3'

services:
    php:
        image: php:7.4-apache
        container_name: my-bookmarks
        volumes: 
            - ./docker:/var/www/html
        ports:
            - "8081:80"
        user: "www-data:www-data"
